version: '3.5'
services:
  app:      
      build: 
        context: .
        args: 
          API_URL: ${API_URL} #baca api url dari .env file
          APP_URL: ${APP_URL}
          APP_NAME: ${APP_NAME}
          APP_LOCALE: ${APP_LOCALE}
          SENTRY_LARAVEL_DSN: ${SENTRY_LARAVEL_DSN}
      restart: always
      container_name: satelit-fe     
      ports:
        - "81:3000"
