version: '3.5'
services:
  app:
      
      build: 
        context: .
        args: 
          API_URL: http://adi-labsatelit-be.rover.digitalservice.id/api/ # tambahkan variable disini agar terbaca
          #API_URL: ${API_URL} # from .env file
          #- API_URL=$API_URL

      #env_file:
      #  - .env-local

      restart: always
      container_name: satelit-fe     
      ports:
        - "81:3000"
